name: ManHuntManHunt
version: ${project.version}
main: com.lifeknight.manhuntmanhunt.ManHuntManHunt
api-version: 1.16
authors: [LifeKnight]
description: Allows for a player to speedrun while another player hunts them. Another player can hunt the player who hunts the speedrunner. Another player can hunt the player who hunts the player who hunts the speedrunner, etc.
commands:
  hunter:
    description: Hunter add/remove/clear commands.
    permission: op
  hunterinfo:
    description: Provides information on who a player is hunting.
  hunterlist:
    description: Lists registered hunters.
  speedrunner:
    description: Speedrunner add/remove/clear/auto commands.
    permission: op
  speedrunnerlist:
    description: Lists registered speedrunners.
  mhmhclear:
    description: Clear speedrunners and hunters.
    permission: op
